CREATE TABLE `payment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`subscriptionId` int,
	`stripePaymentIntentId` varchar(255),
	`stripeInvoiceId` varchar(255),
	`amount` int NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'usd',
	`status` enum('succeeded','pending','failed','refunded') NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payment_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscription_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(50) NOT NULL,
	`displayName` varchar(100) NOT NULL,
	`description` text,
	`priceMonthly` int NOT NULL,
	`priceYearly` int NOT NULL,
	`stripePriceIdMonthly` varchar(255),
	`stripePriceIdYearly` varchar(255),
	`stripeProductId` varchar(255),
	`maxPlatforms` int NOT NULL,
	`maxPostsPerWeek` int NOT NULL,
	`maxTeamMembers` int NOT NULL DEFAULT 1,
	`analyticsRetentionDays` int NOT NULL DEFAULT 7,
	`hasRecurringTemplates` boolean NOT NULL DEFAULT false,
	`hasUnifiedInbox` boolean NOT NULL DEFAULT false,
	`hasSavedReplies` boolean NOT NULL DEFAULT false,
	`hasAutoResponders` boolean NOT NULL DEFAULT false,
	`hasAiReplySuggestions` boolean NOT NULL DEFAULT false,
	`hasVideoContent` boolean NOT NULL DEFAULT false,
	`hasCampaignAnalytics` boolean NOT NULL DEFAULT false,
	`hasAiStrategy` boolean NOT NULL DEFAULT false,
	`hasSubredditTargeting` boolean NOT NULL DEFAULT false,
	`hasExportReports` boolean NOT NULL DEFAULT false,
	`hasPrioritySupport` boolean NOT NULL DEFAULT false,
	`hasApiAccess` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscription_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `subscription_plans_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `user_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`planId` int NOT NULL,
	`status` enum('active','canceled','past_due','trialing','paused') NOT NULL DEFAULT 'active',
	`billingCycle` enum('monthly','yearly') NOT NULL DEFAULT 'monthly',
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`cancelAtPeriodEnd` boolean NOT NULL DEFAULT false,
	`canceledAt` timestamp,
	`postsThisWeek` int NOT NULL DEFAULT 0,
	`weekStartDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_subscriptions_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_subscriptions_userId_unique` UNIQUE(`userId`)
);
